Krypton-Suite/Standard-Toolkit-Demos

Source/Krypton Ribbon Examples/KeyTips + Keyboard Access/Form1.Designer.cs
Source/Krypton Ribbon Examples/KeyTips + Keyboard Access/Form1.cs
Source/Krypton Ribbon Examples/KeyTips + Keyboard Access/Form1.resx
Source/Krypton Ribbon Examples/KeyTips + Keyboard Access/KeyTips + Keyboard Access 2019.csproj
Source/Krypton Ribbon Examples/Krypton Ribbon Examples 2019 - Dev.sln.DotSettings
Source/Krypton Toolkit Examples/KryptonTableLayoutPanel Examples/KryptonTableLayoutPanel Examples 2019.csproj
Source/Krypton Toolkit Examples/Test Clip Base/Form1.cs
Source/Krypton Toolkit Examples/Test Clip Base/Form2.Designer.cs
Source/Krypton Toolkit Examples/Test Clip Base/Test Clip Base 2019.csproj
Source/Krypton Toolkit Examples/Test Clip Base/Test Clip Base 2019.csproj.DotSettings

Tests for https://github.com/Krypton-Suite/Standard-Toolkit/issues/227

- Add Focus override colours

---

Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.cs

Fix for https://github.com/Krypton-Suite/Standard-Toolkit/issues/313

- Update Example project to set RTL Options

---

Source/Krypton Ribbon Examples/Application Menu/Form1.cs
Source/Krypton Ribbon Examples/KeyTips + Keyboard Access/Form1.Designer.cs
Source/Krypton Ribbon Examples/KeyTips + Keyboard Access/Form1.cs
Source/Krypton Ribbon Examples/Quick Access Toolbar/Form1.cs
Source/Krypton Ribbon Examples/Ribbon Controls/Form1.cs

- Resharper vars
Fixes: https://github.com/Krypton-Suite/Standard-Toolkit/issues/372

- Add extra tabs to replicate issue

---

Source/WixInstaller/WixInstaller.net48/Product.wxs
Source/WixInstaller/WixInstaller.net50/Product.wxs
Source/WixInstaller/WixInstaller.net60/BasePath60.wxs
Source/WixInstaller/WixInstaller.net60/Product.wxs

* Fix schoolboy errors :)

---

Source/Krypton Toolkit Examples/.editorconfig
Source/Krypton Toolkit Examples/KryptonButton Examples/KryptonButton Examples 2022.csproj
Source/Krypton Toolkit Examples/KryptonDataGridView Examples/Form2.Designer.cs
Source/Krypton Toolkit Examples/KryptonDataGridView Examples/KryptonDataGridView Examples 2022.csproj
Source/Krypton Toolkit Examples/KryptonDateTimePicker Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonDateTimePicker Examples/KryptonDateTimePicker Examples 2022.csproj

related: https://github.com/Krypton-Suite/Standard-Toolkit/issues/459

- Changes to allow testing of

---

Source/Krypton Toolkit Examples/KryptonDataGridView Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonDataGridView Examples/Form1.cs

Investigate: https://github.com/Krypton-Suite/Standard-Toolkit/issues/445

- Show that a Header tooltip is displayed

---

Source/Krypton Ribbon Examples/Krypton Ribbon Examples 2022 (Debug)  - Dev.sln.DotSettings
Source/Krypton Toolkit Examples/KryptonHelpIcon Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonHelpIcon Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonNumericUpDown Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/Test MessageBox Clipping/Form1.cs
Source/Krypton Toolkit Examples/Test Text Clipping/Form1.Designer.cs
Source/Krypton Toolkit Examples/Test Text Clipping/Form1.cs
Source/Krypton Toolkit Examples/Three Pane Application (Basic)/Form1.Designer.cs
Source/Krypton Toolkit Examples/Three Pane Application (Basic)/Form1.cs

Fixed as part of https://github.com/Krypton-Suite/Standard-Toolkit/issues/502

- Remove the `paletteOffice2013`

---

Source/Krypton Toolkit Examples/Krypton Toolkit Examples 2022 (Debug)  - Dev.sln.DotSettings
Source/Krypton Toolkit Examples/KryptonDataGridView Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonDataGridView Examples/Form1.cs

- Remove redundant controls
part of investigation for https://github.com/Krypton-Suite/Standard-Toolkit/issues/453

- Add multiline values to GridView data

---

Source/.editorconfig
Source/Krypton Docking Examples/Docking Customized/Form1.Designer.cs
Source/Krypton Docking Examples/Docking Customized/Form1.cs
Source/Krypton Docking Examples/Docking Flags/Form1.cs
Source/Krypton Docking Examples/Docking Persistence/Form1.Designer.cs
Source/Krypton Docking Examples/Docking Persistence/Form1.cs
Source/Krypton Docking Examples/External Drag To Docking/ContentTreeView.cs
Source/Krypton Docking Examples/External Drag To Docking/Form1.cs
Source/Krypton Docking Examples/Krypton Docking Examples 2022 (Debug)  - Dev.sln.DotSettings
Source/Krypton Docking Examples/Multi Control Docking/ContentInput.Designer.cs
Source/Krypton Docking Examples/Multi Control Docking/ContentInput.resx
Source/Krypton Docking Examples/Multi Control Docking/Form1.cs
Source/Krypton Docking Examples/Navigator + FloatingWindows/Form1.cs
Source/Krypton Docking Examples/Standard Docking/Form1.Designer.cs
Source/Krypton Docking Examples/Standard Docking/Form1.cs
Source/Krypton Workspace Examples/Memo Editor/Form1.Designer.cs

- Start work on the Docking Examples
- Make sure Workspace Examples work with the new tooltips
- Add some exclusions to to `.editorconfig`

- Make sure code still builds against Alpha branch

---

Source/Krypton Docking Examples/Docking Customized/Form1.cs
Source/Krypton Docking Examples/Docking Flags/Form1.cs
Source/Krypton Docking Examples/Docking Persistence/Form1.cs
Source/Krypton Docking Examples/External Drag To Docking/ContentTreeView.cs
Source/Krypton Docking Examples/External Drag To Docking/Form1.cs
Source/Krypton Docking Examples/Krypton Docking Examples 2022 (Debug)  - Dev.sln.DotSettings
Source/Krypton Docking Examples/Multi Control Docking/Form1.cs
Source/Krypton Docking Examples/Navigator + FloatingWindows/Form1.cs
Source/Krypton Docking Examples/Standard Docking/Form1.cs

- Apply ReSharper coding style
Part of https://github.com/Krypton-Suite/Standard-Toolkit/issues/452 investigations

- Update `Multi Control Demo` to have min Size control set

---

Source/Krypton Toolkit Examples/KryptonDataGridView Examples/Form2.Designer.cs
Source/Krypton Toolkit Examples/KryptonDataGridView Examples/Form2.cs
Source/Krypton Toolkit Examples/KryptonDataGridView Examples/Form2.resx
Source/Krypton Toolkit Examples/KryptonDataGridView Examples/KryptonDataGridView Examples 2022.csproj
Source/Krypton Toolkit Examples/KryptonDataGridView Examples/Properties/Resources.Designer.cs
Source/Krypton Toolkit Examples/KryptonDataGridView Examples/Properties/Resources.resx
Source/Krypton Toolkit Examples/KryptonLinkLabel Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/Test Text Clipping/Form1.Designer.cs

Implements:  https://github.com/Krypton-Suite/Standard-Toolkit/issues/545

- Update demo to show mnemonic firing

---

Source/Krypton Ribbon Examples/Application Menu/Form1.Designer.cs
Source/Krypton Ribbon Examples/Application Menu/Form1.resx

Implements: https://github.com/Krypton-Suite/Standard-Toolkit/issues/74

- Update Form to test the `IgnoreDoubleClickClose`

---

Source/Krypton Explorer/Form1.Designer.cs
Source/Krypton Explorer/Form1.cs
Source/Krypton Explorer/Form1.resx
Source/Krypton Ribbon Examples/Contextual Tabs/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonForm Examples/Form1.Designer.cs

https://github.com/Krypton-Suite/Standard-Toolkit/issues/487

- Update to Forms explorer code base found during

---

Source/Krypton Explorer/Form1.Designer.cs
Source/Krypton Explorer/Form1.cs
Source/Krypton Explorer/Properties/Settings.Designer.cs
Source/Krypton Explorer/Properties/Settings.settings
Source/Krypton Explorer/app.config

* Update KryptonExplorer

---

Source/Krypton Ribbon Examples/Contextual Tabs/Form1.cs
Source/Krypton Ribbon Examples/KeyTips + Keyboard Access/Form1.Designer.cs
Source/Krypton Ribbon Examples/Krypton Ribbon Examples 2022 (Debug)  - Dev.sln.DotSettings
Source/Krypton Ribbon Examples/MDI Ribbon/Form2.cs
Source/Krypton Ribbon Examples/Ribbon Controls/Form1.cs

https://github.com/Krypton-Suite/Standard-Toolkit/issues/441

- Correct some spelling mistakes whilst doing:

---

Source/Krypton Docking Examples/Krypton Docking Examples 2019.sln.DotSettings
Source/Krypton Ribbon Examples/Application Menu/Form1.Designer.cs
Source/Krypton Ribbon Examples/Application Menu/Form1.resx
Source/Krypton Ribbon Examples/Krypton Ribbon Examples 2019 - Dev.sln.DotSettings
Source/Krypton Toolkit Examples/ButtonSpec Playground/ButtonSpec Playground 2022.csproj
Source/Krypton Toolkit Examples/Krypton Toolkit Examples 2019 - Dev.sln.DotSettings
Source/Krypton Toolkit Examples/KryptonButton Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonButton Examples/Form1.resx
Source/Krypton Toolkit Examples/KryptonComboBox Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/KryptonMessageBox Examples 2022.csproj
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Properties/Resources.Designer.cs

- Quite a few changes from other investigations
- Related to
- https://github.com/Krypton-Suite/Standard-Toolkit/issues/70
- https://github.com/Krypton-Suite/Standard-Toolkit/issues/68
- https://github.com/Krypton-Suite/Standard-Toolkit/issues/69

- Make the MessageBox example work with the blur Settings

---

Source/Krypton Ribbon Examples/Application Menu/Form1.Designer.cs
Source/Krypton Ribbon Examples/Application Menu/Form1.resx
Source/Krypton Toolkit Examples/KryptonForm Examples/Form1.Designer.cs

Clear up some compile errors
Add LeftAligned button specs

Alpha 646 left button spec

---

Source/Krypton Toolkit Examples/KryptonForm Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonForm Examples/Form1.cs

Implements: https://github.com/Krypton-Suite/Standard-Toolkit/issues/640

- Add code to allow position of the Form title

---

Source/Krypton Explorer/Form1.Designer.cs
Source/Krypton Explorer/Form1.cs
Source/WixInstaller/WixInstaller.net48/WixInstaller.net48.wax
Source/WixInstaller/WixInstaller.net48/WixInstaller.net48.wixproj
Source/WixInstaller/WixInstaller.net50/WixInstaller.net50.wax
Source/WixInstaller/WixInstaller.net50/WixInstaller.net50.wixproj
Source/WixInstaller/WixInstaller.net60/WixInstaller.net60.wax
Source/WixInstaller/WixInstaller.net60/WixInstaller.net60.wixproj

* Update `KryptonExplorer`

---

Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.cs

* New messagebox options

---

Source/Krypton Toolkit Examples/Krypton UAC Button/Form1.cs
Source/Krypton Toolkit Examples/KryptonColorButton Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonColorButton Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonColorButton Examples/Form1.resx
Source/Krypton Toolkit Examples/KryptonComboBox Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonHelpIcon Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonListBox Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonListView Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonTaskDialog Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonTaskDialog Examples/Form1.cs
Source/Krypton Toolkit Examples/Test MessageBox Clipping/Form1.cs

* Fix fallout from latest changes

* Fix fallout from latest changes

---

Documents/Help/Changelog.md
Source/Krypton Explorer/Form1.Designer.cs
Source/Krypton Explorer/Form1.cs
Source/Krypton Explorer/Properties/Settings.Designer.cs
Source/Krypton Explorer/Properties/Settings.settings
Source/Krypton Explorer/app.config

* Fixed theme bug for `KryptonExplorer`

* Fixed theme bug for `KryptonExplorer`

---

Documents/Help/Changelog.md
Source/Krypton Explorer/Form1.Designer.cs
Source/Krypton Explorer/Form1.cs
Source/Krypton Explorer/Form1.resx
Source/Krypton Explorer/HelpFileLocator.Designer.cs
Source/Krypton Explorer/HelpFileLocator.cs
Source/Krypton Explorer/HelpFileLocator.resx
Source/Krypton Explorer/Krypton Explorer 2022.csproj
Source/Krypton Explorer/Properties/Settings.Designer.cs
Source/Krypton Explorer/Properties/Settings.settings
Source/Krypton Explorer/app.config

* The help file can now be launched via the `KryptonExplorer` (if installed)

Alpha kryptonexplorer

---

Documents/Help/Changelog.md
Source/Krypton Explorer/Form1.Designer.cs
Source/Krypton Explorer/Form1.cs
Source/Krypton Explorer/Form1.resx
Source/Krypton Explorer/Properties/Settings.Designer.cs
Source/Krypton Ribbon Examples/Outlook Mail Clone/Form1.Designer.cs

* Fix `KryptonExplorer` layout
* Add missing icons to links in `KryptonExplorer`

Alpha outlookfix

---

Source/Krypton Explorer/Form1.Designer.cs
Source/Krypton Explorer/Form1.cs
Source/Krypton Explorer/Form1.resx
Source/Krypton Explorer/Properties/Settings.Designer.cs
Source/Krypton Explorer/Properties/Settings.settings
Source/Krypton Explorer/app.config
Source/Krypton Toolkit Examples/IntegratedToolbarExample/Form1.Designer.cs
Source/Krypton Toolkit Examples/IntegratedToolbarExample/IntegratedToolbarExample 2022.csproj
Source/WixInstaller/WixInstaller.net48/WixInstaller.net48.wixproj
Source/WixInstaller/WixInstaller.net60/WixInstaller.net60.wixproj

* Integrated toolbar

---

Documents/Help/Changelog.md
Source/WixInstaller/README.md
Source/WixInstaller/RemovePdbs.xslt
Source/WixInstaller/WixInstaller.net48/CheckFor.Net.wxs
Source/WixInstaller/WixInstaller.net48/KryptonToolkitDemos.wxs
Source/WixInstaller/WixInstaller.net48/License.rtf
Source/WixInstaller/WixInstaller.net48/Product.wxs
Source/WixInstaller/WixInstaller.net48/WixInstaller.net48.wax
Source/WixInstaller/WixInstaller.net48/WixInstaller.net48.wixproj
Source/WixInstaller/WixInstaller.net60/KryptonToolkitDemos.wxs
Source/WixInstaller/WixInstaller.net60/License.rtf
Source/WixInstaller/WixInstaller.net60/Product.wxs
Source/WixInstaller/WixInstaller.net60/WixInstaller.net60.wixproj

* Upgrade to WIX 4

---

Source/Krypton Toolkit Examples/Krypton Toolkit Examples 2022 (Debug)  - Dev.sln.DotSettings
Source/Krypton Toolkit Examples/KryptonBreadCrumb Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonBreadCrumb Examples/Form1.resx
Source/Krypton Toolkit Examples/KryptonBreadCrumb Examples/KryptonBreadCrumb Examples 2022.csproj
Source/Krypton Toolkit Examples/KryptonBreadCrumb Examples/Properties/Resources.Designer.cs

for:
#https://github.com/Krypton-Suite/Standard-Toolkit/issues/962

- Update example to show dropDown buttonSpec

---

Source/Krypton Toolkit Examples/KryptonBorderEdge Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonBreadCrumb Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonButton Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonCheckBox Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonCheckButton Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonDateTimePicker Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonDomainUpDown Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonForm Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonGroup Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonGroupBox Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonHeader Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonHeaderGroup Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonPalette Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonPalette Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonPalette Examples/Form1.resx
Source/Krypton Toolkit Examples/KryptonPanel Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonRadioButton Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonSeparator Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonSplitContainer Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonTableLayoutPanel Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonTrackBar Examples/Form1.cs

- Fix usage of the `DefaultValue` in the examples
#153

- Fix Usage of the Palettebase Properties

---

.gitignore
Source/Krypton Ribbon Examples/Outlook Mail Clone/Form1.Designer.cs
Source/Krypton Ribbon Examples/Outlook Mail Clone/Form1.resx
Source/Krypton Workspace Examples/Advanced Page Drag + Drop/Form1.cs

* Test `RibbonThemeComboBox`

---

Source/Krypton Docking Examples/Docking Customized/ContentPropertyGrid.Designer.cs
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/KryptonMessageBox Examples 2022.csproj
Source/Krypton Toolkit Examples/Test MessageBox Clipping/Form1.cs

Viewable [here](https://1drv.ms/i/s!AnKzT7Em-ox5kN0wpzxZWUHgpQozmA?e=BkiQVk)

* Test KMB text alignment

---

Documents/Help/Changelog.md
Source/Krypton Toolkit Examples/Krypton UAC Button/Form1.cs

* Fix #168

---

Source/Krypton Docking Examples/Docking Customized/Form1.Designer.cs
Source/Krypton Docking Examples/Docking Persistence/Form1.Designer.cs
Source/Krypton Docking Examples/Standard Docking/Form1.Designer.cs
Source/Krypton Navigator Examples/Navigator Palettes/Form1.Designer.cs
Source/Krypton Ribbon Examples/Auto Shrinking Groups/Form1.Designer.cs
Source/Krypton Ribbon Examples/Contextual Tabs/Form1.Designer.cs
Source/Krypton Ribbon Examples/KeyTips + Keyboard Access/Form1.Designer.cs
Source/Krypton Ribbon Examples/MDI Ribbon/Form1.Designer.cs
Source/Krypton Ribbon Examples/Outlook Mail Clone/Form1.Designer.cs
Source/Krypton Ribbon Examples/Quick Access Toolbar/Form1.Designer.cs
Source/Krypton Ribbon Examples/Ribbon + Navigator + Workspace/Form1.Designer.cs
Source/Krypton Ribbon Examples/Ribbon Controls/Form1.Designer.cs
Source/Krypton Ribbon Examples/Ribbon Gallery/Form1.Designer.cs
Source/Krypton Ribbon Examples/Ribbon ToolTips/Form1.Designer.cs
Source/Krypton Toolkit Examples/Custom Control using Renderers/MyUserControl.cs

https://github.com/Krypton-Suite/Standard-Toolkit/issues/1269

- Fix fallout from

---

Source/Krypton Toolkit Examples/Custom Control using Renderers/MyUserControl.cs

method call with invalid number of parameters

MyUserControl: fix LayoutContent call

---

Source/Krypton Toolkit Examples/Custom Control using Renderers/MyUserControl.cs

My previous change was supposed to happen on alpha branch, not master.
This reverts it back in master to previous state.

Revert 950574f (was wrong branch)

---

Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.resx
Source/Krypton Workspace Examples/Advanced Page Drag + Drop/Form1.cs
Source/Krypton Workspace Examples/Advanced Page Drag + Drop/PageDragTreeView.cs
Source/Krypton Workspace Examples/Basic Page Drag + Drop/Form1.cs
Source/Krypton Workspace Examples/Cell Maximize + Restore/Form1.cs
Source/Krypton Workspace Examples/Memo Editor/Form1.Designer.cs
Source/Krypton Workspace Examples/Memo Editor/Form1.cs
Source/Krypton Workspace Examples/Workspace Cell Layout/Form1.cs
Source/Krypton Workspace Examples/Workspace Cell Modes/Form1.cs
Source/Krypton Workspace Examples/Workspace Persistence/Form1.cs

- Fix fallout from the restore of the KMB back to Winform override compatibilty
- Implement Bracket style to code
#https://github.com/Krypton-Suite/Standard-Toolkit/issues/1435

- Fix fallout from the restore of the KMB back to Winform override compatibilty

---

Source/Krypton Ribbon Examples/Ribbon Controls/Form1.Designer.cs
Source/Krypton Ribbon Examples/Ribbon Controls/Form1.cs
Source/Krypton Ribbon Examples/Ribbon Controls/Form1.resx
Source/Krypton Ribbon Examples/Ribbon Controls/Properties/Settings.Designer.cs
Source/Krypton Ribbon Examples/Ribbon Controls/Ribbon Controls 2022.csproj
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonMessageBox Examples/Form1.cs

- Fix the `Ribbon Controls` demo app in the designer and when running

---

Documents/Help/Changelog.md
Source/Krypton Toolkit Examples/Krypton Theme Selector/Form1.cs
Source/Krypton Toolkit Examples/KryptonContextMenu Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonDateTimePicker Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonListView Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonPalette Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonWebBrowser Example/Form1.cs

* Resolved #196

---

Source/Krypton Toolkit Examples/KryptonListView Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonListView Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonListView Examples/Form1.resx
Source/Krypton Toolkit Examples/KryptonListView Examples/KryptonListView Examples 2022.csproj

https://github.com/Krypton-Suite/Standard-Toolkit/issues/1581

- Add disabled Checkbox to aid testing

---

Source/Krypton Ribbon Examples/KryptonGallery Examples/Form1.cs
Source/Krypton Toolkit Examples/ButtonSpec Playground/Form1.cs
Source/Krypton Toolkit Examples/Expanding HeaderGroups (Splitters)/Form1.cs
Source/Krypton Toolkit Examples/Krypton Theme Playground/Form1.Designer.cs
Source/Krypton Toolkit Examples/Krypton Theme Playground/Form1.resx
Source/Krypton Toolkit Examples/KryptonCommandLinkButton Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonPropertyGridExample/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonPropertyGridExample/Form1.resx
Source/Krypton Toolkit Examples/KryptonPropertyGridExample/KryptonPropertyGridExample 2022.csproj
Source/Krypton Toolkit Examples/KryptonPropertyGridExample/Program.cs
Source/Krypton Toolkit Examples/KryptonWrapLabel Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/MDI Application/Form2.cs
Source/Krypton Toolkit Examples/Three Pane Application (Extended)/Form1.cs

- Some project tidying as well
#https://github.com/Krypton-Suite/Standard-Toolkit/issues/632

- Fix fallout from the changes made to the KPropertryGrid

---

Source/Krypton Ribbon Examples/Contextual Tabs/Form1.Designer.cs
Source/Krypton Ribbon Examples/Outlook Mail Clone/Form1.Designer.cs
Source/Krypton Ribbon Examples/Ribbon Controls/Form1.Designer.cs
Source/Krypton Toolkit Examples/ButtonSpec Playground/ButtonSpec Playground 2022.csproj
Source/Krypton Toolkit Examples/Custom Control using Palettes/MyUserControl.cs
Source/Krypton Toolkit Examples/Custom Control using Renderers/MyUserControl.cs
Source/Krypton Toolkit Examples/Krypton Scrollbars/Form1.cs
Source/Krypton Toolkit Examples/Krypton Toolkit Examples 2022 (Debug)  - Dev.sln.DotSettings
Source/Krypton Toolkit Examples/KryptonComboBox Examples/KryptonComboBox Examples 2022.csproj
Source/Krypton Toolkit Examples/KryptonContextMenu Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonContextMenu Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonContextMenu Examples/Form1.resx
Source/Krypton Toolkit Examples/KryptonDomainUpDown Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonFolderBrowserDialog Example/Form1.cs
Source/Krypton Toolkit Examples/KryptonHelpIcon Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonLabel Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonLinkLabel Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonNumericUpDown Examples/Form1.Designer.cs
Source/Krypton Toolkit Examples/KryptonOutlookGrid Example/Form1.cs
Source/Krypton Toolkit Examples/KryptonScrollbar Examples/Form1.cs
Source/Krypton Toolkit Examples/KryptonStringCollectionEditor Examples 2022/Program.cs
Source/Krypton Toolkit Examples/KryptonToastNotification Examples/BasicNotification.cs
Source/Krypton Toolkit Examples/KryptonToastNotification Examples/MainForm.cs
Source/Krypton Toolkit Examples/KryptonToastNotification Examples/UserInputNotification.cs
Source/Krypton Toolkit Examples/Test Clip Base/Form2.cs

https://github.com/Krypton-Suite/Standard-Toolkit/issues/1749

- Updates to allow todays alpha to build

---

Documents/Help/Changelog.md
README.md
Source/Krypton Explorer/Form1.Designer.cs
Source/Krypton Explorer/Form1.cs
Source/Krypton Explorer/Krypton Explorer 2022 - Dev.sln
Source/Krypton Explorer/Krypton Explorer 2022.csproj
Source/WixInstaller/WixInstaller.net48/Product.wxs
Source/WixInstaller/WixInstaller.net48/WixInstaller.net48.wixproj
Source/WixInstaller/WixInstaller.net80/Product.wxs
Source/WixInstaller/WixInstaller.net80/WixInstaller.net80.wixproj
Source/WixInstaller/WixInstaller.net90/Product.wxs
Source/WixInstaller/WixInstaller.net90/WixInstaller.net90.wixproj

- Update release version if the installers
#238

- Make sure that the applications page can launch something
